---
# tasks file for prometheus

- name: Create group prometheus
  group:
    name: prometheus

- name: Create user prometheus
  user:
    name: prometheus
    group: prometheus

- name: Get prometheus user id
  command: 'id -u prometheus'
  register: prometheus_user_id
  failed_when: prometheus_user_id.rc != 0
  changed_when: false

- name: Set fact 
  set_fact:
    prometheus_user: '{{ prometheus_user_id.stdout }}'

- name: Create prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755
  loop:
    - /opt/prometheus
    - /opt/prometheus/data

- name: Upload the docker-compose.yml file
  template:
    src: templates/docker-compose.yaml.j2
    dest: /opt/prometheus/docker-compose.yaml
    owner : prometheus
    group: prometheus
    mode: 0755

- name: Upload the prometheus.yaml file
  template:
    src: templates/prometheus.yaml.j2
    dest: /opt/prometheus/prometheus.yaml
    owner : prometheus
    group: prometheus
    mode: 0755

- name: Start prometheus container
  community.docker.docker_compose_v2:
    project_src: /opt/prometheus/
    state: present